### ISSUE TITLE
请问一下fa home等样式怎么才能恢复

### ISSUE THREAD

**Issue by zi-done** [7ye/maupassant-hexo#3]
![TIM图片20171216234018.png](https://i.loli.net/2017/12/16/5a353e9a9ccde.png)
你知道我这个为什么不显示吗
![TIM图片20171216234027.png](https://i.loli.net/2017/12/16/5a353e9a9008e.png)
这边加了
![TIM图片20171216234033.png](https://i.loli.net/2017/12/16/5a353e9ac077f.png)
base.jade这东西也引用了

**Comment by 7ye** [comment]
导航菜单并没有添加图标的功能哟，直接加图标名肯定不会显示的，没地方引用这个样式
